"""The I/O runtime for aarch64.

Generated by `bin/pl4g-runtime` from `runtime/io.c`; do not edit.
A test recompiles the C and compares, so a module older than the
source it was made from fails the suite.
"""

from __future__ import annotations

from . import Blob, Patch, Piece

BLOB = Blob(
    triple="aarch64-linux-gnu",
    pieces=(
        Piece(name=".text", alignment=4,
              writable=False, executable=True,
              contents=bytes.fromhex(
                  "e40303aae30302aae203012a2100805201000014a41000b4ff0302d1"
                  "080040f9e90300aa1f0500f1000a0054a81000b500e4006f48008052"
                  "ed0301aaee0302aaef0303aaf00304aa280100f900018052e1030091"
                  "ff3b00f928358052e2031faae00300ade3031faae4031faae00301ad"
                  "e5031faae00302ade01b803d010000d4800df8b7eb334029e84340b9"
                  "ea6740b9e40300aae0031faae5031faa6200805201090b8b4a110c8b"
                  "c81b805223009052010000d46ce57ad3eb0300aae0031faac81b8052"
                  "e1030aaa62008052230090520500a152010000d4ea0300aae0031faa"
                  "c81b8052e1030caa62008052230090520500a252010000d4cb09f8b7"
                  "aa09f8b78009f8b7e83340b9ec4340b9600d084e420d084ee11740fd"
                  "e32b40fd6801088b6b010c8be3030faa282d02a9e85b40b9eb6740b9"
                  "0010a12e4110a32ee2030eaa4801088b4a010b8be1030daa28a904a9"
                  "28008052281100a9e40310aa201900f92005803d2181833c2ba941a9"
                  "287c7ed30c0000908c01009100e4006f886968384a0140b96bfddf88"
                  "2c1940f96a010a0a6b0500118c190a8b8081823c9f1d00f98001803d"
                  "837d01a988010039281540f9820500b9841900b98a1100f92c0d40f9"
                  "0a592ab88bfd9f88200540f948358052210080522200805223008052"
                  "e4031faae5031faa010000d4c001f8b728a943a9080140b94afddf88"
                  "1f010a6b60feff542aad44a9291d40f94a0140b94a01080a08050011"
                  "6a512a8b400980b928fd9f88ff030291c0035fd6e0031faac0035fd6"
                  "e40310aae3030faae2030eaae1030daa0800009008010091407c4093"
                  "0849218be10303aae20304aae3031faae4031faae5031faa08054079"
                  "010000d4ff030291c0035fd6e40303aae30302aae203012ae1031f2a"
                  "64ffff17")),
        Piece(name=".rodata.cst8", alignment=2,
              writable=False, executable=False,
              contents=bytes.fromhex(
                  "16003f0017004000")),
    ),
    symbols={
        "pl4g_io_read": (0, 628),
        "pl4g_io_write": (0, 0),
    },
    patches=(
        Patch(piece=0, offset=368, kind="aarch64_adr_page21",
              target=1, addend=0),
        Patch(piece=0, offset=372, kind="aarch64_add_lo12",
              target=1, addend=0),
        Patch(piece=0, offset=576, kind="aarch64_adr_page21",
              target=1, addend=0),
        Patch(piece=0, offset=580, kind="aarch64_add_lo12",
              target=1, addend=0),
    ),
)
