"""The I/O runtime for riscv64.

Generated by `bin/pl4g-runtime` from `runtime/io.c`; do not edit.
A test recompiles the C and compares, so a module older than the
source it was made from fails the suite.
"""

from __future__ import annotations

from . import Blob, Patch, Piece

BLOB = Blob(
    triple="riscv64-linux-gnu",
    pieces=(
        Piece(name=".text", alignment=2,
              writable=False, executable=True,
              contents=bytes.fromhex(
                  "3687b2862e8685451703000067008300630b071e757122e526e1b282"
                  "2a8808610546630cc5106315051eae8e368fba8f094502e402e802ec"
                  "02f002f402f802fc82e082e482e882ec82f082f482f882fc9308901a"
                  "2c002330a80021450146814601478147730000006341051a2a878147"
                  "0145036e81000363c100836581048363c106a1669308e00d13162e00"
                  "b2950d46850612031a0e1e9373000000aa839308e00d0d46b7070008"
                  "9a850145730000002a839308e00d0d46b7070010f285014573000000"
                  "63c3031463410314634f051283650103036641038366810383678104"
                  "b388b300338ec300b384d300be93836581050366c105836601068367"
                  "c1069a951a969a969a970544233088002334e80023381801233cc801"
                  "23309802233478022338a802233cb8022330c8042334d8042338f804"
                  "7e87fa86f6858a05170500000336880183370802130505002e958348"
                  "05008c4310420f00300283370803b374b600130316009395040213d4"
                  "050213d5a501f9813e9523300500233c05002334050223380502233c"
                  "05028337880103368802230015012322550014e918cd2334050000f1"
                  "b29584c10f00100323a067009308a01a854601478147033588008545"
                  "0546730000006345050603358803033608048365050008421b860500"
                  "0f003002e30da6fc033588040336080503650500833688036d8d1205"
                  "3295084585050f0010038cc235a0014582807e87fa86f6858a051705"
                  "0000130505002e9583582500b6853a86814601478147168573000000"
                  "2a648a64496182803687b2862e86814517030000670003dd")),
        Piece(name=".rodata", alignment=8,
              writable=False, executable=False,
              contents=bytes.fromhex(
                  "58000000000000000800000000000000000000000000000008000000"
                  "00000000080000000000000008000000000000001000000000000000"
                  "08000000000000001800000000000000080000000000000020000000"
                  "00000000080000000000000028000000000000000800000000000000"
                  "30000000000000000800000000000000380000000000000008000000"
                  "00000000400000000000000008000000000000004800000000000000"
                  "080000000000000050000000000000000800000000000000")),
        Piece(name=".rodata.cst8", alignment=2,
              writable=False, executable=False,
              contents=bytes.fromhex(
                  "16003f0017004000")),
    ),
    symbols={
        "pl4g_io_read": (0, 568),
        "pl4g_io_shape": (1, 0),
        "pl4g_io_write": (0, 0),
    },
    patches=(
        Patch(piece=0, offset=316, kind="riscv_pcrel_hi20",
              target=2, addend=0),
        Patch(piece=0, offset=328, kind="riscv_pcrel_lo12_i",
              target=2, addend=0, measured_from=-12),
        Patch(piece=0, offset=530, kind="riscv_pcrel_hi20",
              target=2, addend=0),
        Patch(piece=0, offset=534, kind="riscv_pcrel_lo12_i",
              target=2, addend=0, measured_from=-4),
    ),
)
