"""The I/O runtime for x86_64.

Generated by `bin/pl4g-runtime` from `runtime/io.c`; do not edit.
A test recompiles the C and compares, so a module older than the
source it was made from fails the suite.
"""

from __future__ import annotations

from . import Blob, Patch, Piece

BLOB = Blob(
    triple="x86_64-linux-gnu",
    pieces=(
        Piece(name=".text", alignment=16,
              writable=False, executable=True,
              contents=bytes.fromhex(
                  "4989c84889d189f2be01000000eb01904d85c00f842d010000554157"
                  "415641554154534889fb488b074883f8010f848b0100004885c00f85"
                  "e300000089742484895424804889cd4d89c548c703020000000f57c0"
                  "0f114424980f114424880f114424b80f114424a80f114424d80f1144"
                  "24c80f114424e848c74424f800000000488d742488b8a9010000bf08"
                  "00000031d24531d24531c04531c90f054885c078704989c08b4424c8"
                  "448b642488448b74248c4a8d34a08b4424ec49c1e6044901c649c1e4"
                  "06b809000000ba0300000041ba0180000031ff4531c90f054989c7b8"
                  "0900000041b90000000831ff4c89f60f054989c6b80900000041b900"
                  "00001031ff4c89e60f054c89f94c09f14809c179384d89e84889e98b"
                  "5424808b74248489f0488d35000000000fb74486024863fa4889ce4c"
                  "89c24531d24531c04531c90f05e94201000031c0c34c8943088b4c24"
                  "b04c01f948894b108b4c24b44c01f948894b188b4c24b84c01f94889"
                  "4b208b4c24c84c01f948894b28488943308b4424d84c01f048894338"
                  "8b4424dc4c01f0488943408b4424e04c01f0488943488b4424ec4c01"
                  "f04889435048c703010000004d89e84889e98b5424808b74248489f0"
                  "488d35000000000fb60486488b7318488b7b208b368b3f21f74c8b4b"
                  "304989fa49c1e2060f57c0430f1104114bc744111800000000430f11"
                  "4411284bc7441138000000004388041143895411044b894c11104789"
                  "4411184b897c1120488b4328893cb8488b4318ffc68930be01000000"
                  "41ba01000000662e0f1f840000000000488b7b08b8aa010000ba0100"
                  "00004531c04531c90f054885c0782d488b4338488b53408b088b0239"
                  "c174d5488b5338488b4348488b73508b0021c848c1e0044863440608"
                  "ffc1890a5b415c415d415e415f5dc3666666662e0f1f840000000000"
                  "4989c84889d189f231f6e961fdffff")),
        Piece(name=".rodata.cst8", alignment=2,
              writable=False, executable=False,
              contents=bytes.fromhex(
                  "1600000017000100")),
    ),
    symbols={
        "pl4g_io_read": (0, 672),
        "pl4g_io_write": (0, 0),
    },
    patches=(
        Patch(piece=0, offset=292, kind="pcrel32_at_field",
              target=1, addend=-4),
        Patch(piece=0, offset=451, kind="pcrel32_at_field",
              target=1, addend=-4),
    ),
)
