"""Symbolic names of the diagnostics.

Generated from ``share/diagnostics.json`` by ``bin/pl4g-gen-diag-ids``.
Do not edit; change the catalog and regenerate.
"""

from typing import Final

from .catalog import DiagID


# 1000-1099: driver and command line
IMPL_CLI_MISSING_OUTPUT: Final[DiagID] = 1001
IMPL_CLI_NO_INPUT: Final[DiagID] = 1002
IMPL_CLI_BAD_SUFFIX: Final[DiagID] = 1003
IMPL_CLI_UNKNOWN_OPTION: Final[DiagID] = 1004
IMPL_CLI_DUPLICATE_OUTPUT: Final[DiagID] = 1005
IMPL_CLI_NOT_IMPLEMENTED: Final[DiagID] = 1006
IMPL_CLI_MISSING_ARGUMENT: Final[DiagID] = 1007
IMPL_CLI_BAD_ARGUMENT: Final[DiagID] = 1008
IMPL_CLI_UNKNOWN_TARGET: Final[DiagID] = 1009
IMPL_CLI_UNKNOWN_WARNING: Final[DiagID] = 1010

# 1100-1199: input and output files
IMPL_INPUT_UNREADABLE: Final[DiagID] = 1101
IMPL_OUTPUT_UNWRITABLE: Final[DiagID] = 1102

# 2000-2099: lexical structure
LANG_SYNTAX_INVALID_UTF8: Final[DiagID] = 2001
LANG_SYNTAX_UNEXPECTED_CHAR: Final[DiagID] = 2002
LANG_SYNTAX_UNTERMINATED_STRING: Final[DiagID] = 2003
LANG_SYNTAX_BAD_ESCAPE: Final[DiagID] = 2004
LANG_SYNTAX_ASCII_SUBSTITUTE: Final[DiagID] = 2005
LANG_SYNTAX_INTEGER_RANGE: Final[DiagID] = 2006
LANG_SYNTAX_BAD_LITERAL_SUFFIX: Final[DiagID] = 2007
LANG_SYNTAX_LONELY_NEGATIVE: Final[DiagID] = 2008

# 2100-2199: layout and block style
LANG_SYNTAX_INCONSISTENT_INDENT: Final[DiagID] = 2101
LANG_SYNTAX_MIXED_BLOCK_STYLE: Final[DiagID] = 2102
LANG_SYNTAX_TAB_INDENT: Final[DiagID] = 2103

# 3000-3199: syntax
LANG_SYNTAX_UNEXPECTED_TOKEN: Final[DiagID] = 3001
LANG_FUNCDEF_EXPECTED_ARROW: Final[DiagID] = 3002
LANG_FUNCDEF_EXPECTED_BLOCK: Final[DiagID] = 3003
LANG_FILESTRUCT_UNEXPECTED_TOPLEVEL: Final[DiagID] = 3004
LANG_FUNCDEF_DUPLICATE_PARAMETER: Final[DiagID] = 3005
LANG_VARDEF_EXPECTED_COLON: Final[DiagID] = 3006
LANG_VARDEF_MISSING_INITIALIZER: Final[DiagID] = 3007
LANG_ASSIGN_EXPECTED_ARROW: Final[DiagID] = 3008

# 3200-3299: attributes
LANG_ATTR_UNKNOWN: Final[DiagID] = 3201
LANG_ATTR_DUPLICATE: Final[DiagID] = 3202
LANG_ATTR_BAD_ARGUMENTS: Final[DiagID] = 3203
LANG_ATTR_NOT_APPLICABLE: Final[DiagID] = 3204
LANG_ATTR_CONFLICT: Final[DiagID] = 3205
LANG_ATTR_EXPECT_NOT_RAISED: Final[DiagID] = 3206
LANG_ATTR_EXPECT_UNKNOWN_NUMBER: Final[DiagID] = 3207

# 4000-4199: names and modules
LANG_FILESTRUCT_DUPLICATE_DEFINITION: Final[DiagID] = 4001
LANG_FILESTRUCT_PREVIOUS_DEFINITION: Final[DiagID] = 4002
LANG_FILESTRUCT_UNDEFINED_NAME: Final[DiagID] = 4003
LANG_VARDEF_NOT_MUTABLE: Final[DiagID] = 4004
LANG_VARDEF_DEFINED_HERE: Final[DiagID] = 4005
LANG_VARDEF_VALUE_UNUSED: Final[DiagID] = 4006
LANG_VARDEF_TOPLEVEL_UNREAD: Final[DiagID] = 4007

# 4200-4399: types
LANG_TYPE_UNKNOWN: Final[DiagID] = 4201
LANG_TYPE_RETURN_MISMATCH: Final[DiagID] = 4202
LANG_TYPE_INITIALIZER_MISMATCH: Final[DiagID] = 4203
LANG_TYPE_ASSIGNMENT_MISMATCH: Final[DiagID] = 4204

# 4400-4599: special functions
LANG_FUNCDEF_SPECIAL_NO_STARTUP: Final[DiagID] = 4401
LANG_FUNCDEF_SPECIAL_MULTIPLE_STARTUP: Final[DiagID] = 4402
LANG_FUNCDEF_SPECIAL_PREVIOUS_STARTUP: Final[DiagID] = 4403
LANG_FUNCDEF_SPECIAL_BAD_SIGNATURE: Final[DiagID] = 4404
LANG_FUNCDEF_SPECIAL_BAD_CTOR_SIGNATURE: Final[DiagID] = 4405

# 5000-5299: control flow and returns
LANG_FUNCDEF_RETURN_UNREACHABLE: Final[DiagID] = 5001
LANG_FUNCDEF_RETURN_REDUNDANT: Final[DiagID] = 5002
LANG_FUNCDEF_RETURN_MISSING: Final[DiagID] = 5003
LANG_FUNCDEF_RETURN_VALUE_IN_VOID: Final[DiagID] = 5004

# 8500-8999: code generation and inline assembly
IMPL_BACKEND_UNSUPPORTED: Final[DiagID] = 8501
IMPL_BACKEND_UNENCODABLE: Final[DiagID] = 8502

# 9000-9499: image generation and incremental compilation
IMPL_IMAGE_UNDEFINED_SYMBOL: Final[DiagID] = 9001
IMPL_IMAGE_VALUE_OUT_OF_RANGE: Final[DiagID] = 9002

# 9900-9999: internal compiler errors
IMPL_INTERNAL_ERROR: Final[DiagID] = 9901
IMPL_UNIMPLEMENTED_FEATURE: Final[DiagID] = 9902
